-- ============================================================================
-- Supabase (PostgreSQL) schema for ZenRoute backend
-- Run this in Supabase SQL Editor before starting the server.
-- ============================================================================

create extension if not exists pgcrypto;

create table if not exists public.users (
  id bigint generated by default as identity primary key,
  name text not null,
  email text not null unique,
  password text not null,
  phone text,
  role smallint not null default 0, -- 0 = Passenger, 1 = Driver
  address text,
  plate_number text unique,
  license_number text unique,
  jeepney_id text unique,
  vehicle_type text default 'Jeepney',
  vehicle_model text,
  vehicle_color text,
  is_verified boolean not null default false,
  is_active boolean not null default true,
  is_online boolean not null default false,
  current_passengers integer not null default 0,
  standing_passengers integer not null default 0,
  max_capacity integer not null default 26,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint users_role_check check (role in (0, 1)),
  constraint users_capacity_non_negative check (current_passengers >= 0 and standing_passengers >= 0),
  constraint users_standing_le_current check (standing_passengers <= current_passengers),
  constraint users_max_capacity_exact check (max_capacity = 26)
);

create table if not exists public.login_history (
  id bigint generated by default as identity primary key,
  user_id bigint references public.users(id) on delete set null,
  role smallint,
  email text not null,
  ip_address text,
  user_agent text,
  login_status text not null check (login_status in ('success', 'failed')),
  failure_reason text,
  created_at timestamptz not null default now()
);

create table if not exists public.driver_locations (
  id bigint generated by default as identity primary key,
  driver_id bigint not null references public.users(id) on delete cascade,
  jeepney_id text,
  latitude numeric(10, 8) not null,
  longitude numeric(11, 8) not null,
  accuracy numeric(10, 2),
  speed numeric(10, 2),
  heading numeric(5, 2),
  created_at timestamptz not null default now()
);

create table if not exists public.saved_locations (
  id bigint generated by default as identity primary key,
  user_id bigint not null references public.users(id) on delete cascade,
  name text not null,
  latitude numeric(10, 8) not null,
  longitude numeric(11, 8) not null,
  address text,
  type text not null default 'custom' check (type in ('home', 'work', 'school', 'custom')),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.password_reset_tokens (
  id bigint generated by default as identity primary key,
  user_id bigint not null references public.users(id) on delete cascade,
  token text not null unique,
  expires_at timestamptz not null,
  used boolean not null default false,
  created_at timestamptz not null default now()
);

create index if not exists idx_users_email on public.users(email);
create index if not exists idx_users_role on public.users(role);
create index if not exists idx_users_role_online on public.users(role, is_online);
create index if not exists idx_users_jeepney_id on public.users(jeepney_id);
create index if not exists idx_login_history_user_id on public.login_history(user_id);
create index if not exists idx_login_history_email on public.login_history(email);
create index if not exists idx_login_history_created_at on public.login_history(created_at);
create index if not exists idx_driver_locations_driver_id on public.driver_locations(driver_id);
create index if not exists idx_driver_locations_jeepney_id on public.driver_locations(jeepney_id);
create index if not exists idx_driver_locations_created_at on public.driver_locations(created_at);
create index if not exists idx_saved_locations_user_id on public.saved_locations(user_id);
create index if not exists idx_saved_locations_type on public.saved_locations(type);
create index if not exists idx_password_reset_token on public.password_reset_tokens(token);
create index if not exists idx_password_reset_expires on public.password_reset_tokens(expires_at);

create or replace function public.set_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists trg_users_updated_at on public.users;
create trigger trg_users_updated_at
before update on public.users
for each row execute procedure public.set_updated_at();

drop trigger if exists trg_saved_locations_updated_at on public.saved_locations;
create trigger trg_saved_locations_updated_at
before update on public.saved_locations
for each row execute procedure public.set_updated_at();
